#!/usr/bin/env python2

import sys
from subprocess import Popen, PIPE, STDOUT

def main(text):
    flags = sys.argv[1:]

    if '-s' in flags:
        text = text.replace('\n', ' ')
        text = text.replace('\r', ' ')

    lines = [l for l in text.split('\n') if l.strip() != '']
    result = []
    for line in lines:
        result.append(toid(line))

    if len(result) > 1:
        for line in result:
            print line
    else:
        print result[0],
        if '-c' in flags:
            copy_to_clip(result[0])



def copy_to_clip(text):
    p = Popen(['xclip', '-selection' , 'clipboard', '-i'], stdout=PIPE, stdin=PIPE, stderr=STDOUT)    
    p.stdin.write(text)    
    p.stdin.close()

def toid(text, delim='-'):
    valid = '0123456789.abcdefghijklmnopqrstuvwxyz'
    valid = '0123456789abcdefghijklmnopqrstuvwxyz'
    result = []
    for c in text.lower():
        if c in valid:
            result.append(c)
        else:
            result.append(delim)
    result = ''.join(result)
    result = result.strip()
    while (delim + delim) in result:
        result = result.replace(delim+delim, delim)
    if len(result) > 0 and result[-1] == delim:
        return result[:-1]
    return result


def getClipboard():
    import commands
    try:
        _, clipboard = commands.getstatusoutput('xclip -o -selection clipboard')
        return clipboard
    except Exception as ex:
        pass
#         log.notify('EXCEPTION OCCURED', fx)


text = getClipboard()
main(text)
